openapi: 3.0.1
info:
    title: Mealwise Plugin
    description: A plugin that allows the user to create and manage a TODO list using ChatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
    version: "v1"
servers:
    - url: https://mealwise.onrender.com
paths:
  /get_product_info:
    get:
      operationId: getProductInfo,
      summary: Get product information from the Kroger API.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    description:
                      type: string
                    price:
                      type: string
                    hasPromo:
                      type: boolean
                    promoPrice:
                      type: number
                    location:
                      type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
