openapi: 3.0.1
info:
  title: Meal Price Plugin
  description: A plugin that fetches product prices from Kroger.
  version: 'v1'
servers:
  - url: https://mealwise.onrender.com
paths:
  /mealwise/{prompt}:
    get:
      operationId: promptEndpoint
      summary: Get mealwise prompt
      parameters:
        - name: prompt
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /get_product_info:
    get:
      operationId: getProductInfo
      summary: Get product information
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    description:
                      type: string
                    price:
                      type: string
                    hasPromo:
                      type: boolean
                    promoPrice:
                      type: number
                    location:
                      type: string